link_saver/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('links.urls')),
]

links/urls.py
from django.urls import path
from .views import index, link_create, category_create

app_name = 'links'

urlpatterns = [
    path('categories/create/', category_create, name='category_create'),
    path('links/add/', link_create, name='link_create'),
    path('', index, name='index'),
]

links/models.py
from django.db import models
from django.db.utils import IntegrityError
from model_utils.models import TimeStampedModel


class Category(TimeStampedModel):
    name = models.CharField(max_length=120, verbose_name='Category name', unique=True)

    def __str__(self):
        return self.name

class Link(TimeStampedModel):
    # title
    # short_desc / note
    url = models.URLField(verbose_name= 'URL')
    times_saved = models.PositiveIntegerField(default=1)
    categories = models.ManyToManyField(Category)

    def __str__(self):
        return self.url

links/forms.py
from django import forms
from .models import Link, Category

class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ('name',)

class LinkForm(forms.ModelForm):
    class Meta:
        model = Link
        fields = ('url', 'categories',)
 

links/views.py
from django.shortcuts import render, redirect

from .forms import LinkForm, CategoryForm
from .models import Link


def index(request):
    links = Link.objects.all()
    context = {
        'links': links,
    }
    return render(request, 'links/index.html', context)

def link_create(request):
    if request.method == 'POST':
        link_form = LinkForm(request.POST)
        if link_form.is_valid():
            cleaned_url = link_form.cleaned_data['url']
            if Link.objects.filter(url=cleaned_url).exists():
                existent_link = Link.objects.get(url=cleaned_url)
                existent_link.categories.add(*link_form.cleaned_data['categories'])
                existent_link.times_saved += 1                
                existent_link.save()                                
            else:
                link_form.save()
            return redirect('links:link_create')
    else:
        link_form = LinkForm()
    context = {
        'link_form': link_form,
    }
    return render(request, 'links/link_form.html', context)

def category_create(request):
    if request.method == 'POST':
        category_form = CategoryForm(request.POST)
        if category_form.is_valid():
            category_form.save()
            return redirect('links:category_create')
    else:
        category_form = CategoryForm()
    context = {
        'category_form': category_form,
    }
    return render(request, 'links/category_create.html', context)

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title>link_saver</title>
  </head>
  <body>
      {% block content %}

      {% endblock %}


    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    -->
  </body>
</html>

templates/links/category_create.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
<div class="container">
    <h2 class="pt-4 pb-4">Add new category</h2>
  <form method="post" novalidate>
    {% csrf_token %}
    {{ category_form|crispy }}
    
    <div class="btns mt-4">
    <button type="submit" class="btn btn-success">Add category</button>
    <a href="{% url 'links:link_create' %}" role="button" class="ms-2 btn btn-secondary">Back</a>
    </div>
  </form>   
</div>
{% endblock %}

templates/links/index.html
{% extends 'base.html' %}

{% block content %}
<div class="container">     
    <h2 class="pt-4 pb-4">link_saver Saving Your Life</h2>
    <a href="{% url 'links:link_create' %}" role="button" class="float-end btn btn-secondary mb-4">Add link</a>
<table class="table table-hover mt-5">
    <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">URL</th>
      <th scope="col">Categories</th>
      <th scope="col"># times saved</th>
    </tr>
  </thead>
    <tbody>
        {% for link in links %}
        <tr>
          <th scope="row">{{ forloop.counter }}</th>
          <td>{{ link.url }}</td>
          <td>{{ link.categories.all|join:", " }}</td>
          <td>{{ link.times_saved }}</td>
        </tr>
        {% endfor %}           
      </tbody>
  </table>
</table>
{% endblock %}

templates/links/link_form.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
<div class="container">
    <h2 class="pt-4 pb-4">Add new link</h2>
  <form method="post" novalidate>
    {% csrf_token %}
    {{ link_form|crispy }}
    <a class='float-end mb-4' href="{% url 'links:category_create' %}">No category you need yet?</a>
    <div class="btns mt-4">
    <button type="submit" class="btn btn-success">Add link</button>
    <a href="{% url 'links:index' %}" role="button" class="ms-2 btn btn-secondary">Back</a>
    </div>
  </form>   
</div>
{% endblock %}